apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: bootnode
  namespace: {{ .Release.Namespace }}

  labels:
    app: bootnode
    app.kubernetes.io/component: bootnode

spec:
  serviceName: bootnode

  replicas: 1

  selector:
    matchLabels:
      app: bootnode

  template:
    metadata:
      labels:
        app: bootnode
        app.kubernetes.io/component: bootnode

    spec:

      securityContext:
        fsGroup: 1000

      containers:
        - name: bootnode

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - "--config-file=/etc/besu/config.toml"
            - "--genesis-file=/etc/genesis/genesis.json"
            - "--data-path=/data"

            - "--p2p-enabled=true"
            - "--p2p-port=30303"

            - "--rpc-http-enabled=false"
            - "--rpc-ws-enabled=false"

            - "--discovery-enabled=true"

            - "--host-allowlist=*"

          ports:
            - name: discovery
              containerPort: 30303
              protocol: UDP

            - name: rlpx
              containerPort: 30303
              protocol: TCP

          volumeMounts:
            - name: genesis
              mountPath: /etc/genesis
              readOnly: true

            - name: validator-config
              mountPath: /etc/besu/config.toml
              subPath: config.toml
              readOnly: true

            - name: static-nodes
              mountPath: /etc/besu/static-nodes.json
              subPath: static-nodes.json
              readOnly: true

            - name: data
              mountPath: /data

      volumes:
        - name: genesis
          configMap:
            name: besu-genesis-configmap

        - name: validator-config
          configMap:
            name: besu-validators-config-toml-configmap

        - name: static-nodes
          configMap:
            name: besu-static-nodes-json-configmap

        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service

metadata:
  name: bootnode
  namespace: {{ .Release.Namespace }}

spec:
  clusterIP: None

  selector:
    app: bootnode

  ports:
    - name: discovery
      port: 30303
      targetPort: 30303
      protocol: UDP

    - name: rlpx
      port: 30303
      targetPort: 30303
      protocol: TCP