apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: besu-validators-pdb
  namespace: {{ .Release.Namespace }}

  labels:
    {{- include "besu-marketplace.labels" . | nindent 4 }}
    app.kubernetes.io/component: validator

spec:
  minAvailable: {{ .Values.validators.pdb.minAvailable }}

  selector:
    matchLabels:
      app.kubernetes.io/component: validator