apiVersion: v1
kind: Secret

metadata:
  name: besu-network-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:

  validator1.key: |
    YOUR_VALIDATOR1_PRIVATE_KEY

  validator2.key: |
    YOUR_VALIDATOR2_PRIVATE_KEY

  validator3.key: |
    YOUR_VALIDATOR3_PRIVATE_KEY

  validator4.key: |
    YOUR_VALIDATOR4_PRIVATE_KEY

  rpc.key: |
    YOUR_RPC_PRIVATE_KEY