apiVersion: v1
kind: Secret

metadata:
  name: besu-network-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  validator1.key: "{{ .Values.secrets.validator1Key }}"
  validator2.key: "{{ .Values.secrets.validator2Key }}"
  validator3.key: "{{ .Values.secrets.validator3Key }}"
  validator4.key: "{{ .Values.secrets.validator4Key }}"
  rpc.key: "{{ .Values.secrets.rpcKey }}"