{{- range .Values.validatorsList }}

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}

  labels:
    app: {{ .name }}
    app.kubernetes.io/name: besu
    app.kubernetes.io/component: validator
    app.kubernetes.io/managed-by: Helm
    {{- with $.Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

  {{- with $.Values.commonAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}

spec:
  serviceName: {{ .name }}

  replicas: {{ $.Values.validators.replicaCount }}

  podManagementPolicy: Parallel

  revisionHistoryLimit: 3

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  selector:
    matchLabels:
      app: {{ .name }}

  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/name: besu
        app.kubernetes.io/component: validator

        {{- with $.Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}

      annotations:
        {{- if $.Values.validators.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $.Values.validators.metrics.port }}"
        {{- end }}

        {{- with $.Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}

    spec:

      terminationGracePeriodSeconds: {{ $.Values.validators.terminationGracePeriodSeconds }}

      {{- if $.Values.validators.priorityClassName }}
      priorityClassName: {{ $.Values.validators.priorityClassName }}
      {{- end }}

      securityContext:
        fsGroup: {{ $.Values.securityContext.fsGroup }}

      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with $.Values.validators.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with $.Values.validators.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      {{- if $.Values.validators.antiAffinity.enabled }}
      affinity:
        podAntiAffinity:

          {{- if eq $.Values.validators.antiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - validator
              topologyKey: kubernetes.io/hostname

          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - validator
                topologyKey: kubernetes.io/hostname
          {{- end }}

      {{- else if $.Values.validators.affinity }}
      affinity:
        {{ toYaml $.Values.validators.affinity | nindent 8 }}
      {{- end }}

      {{- if $.Values.validators.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ $.Values.validators.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ $.Values.validators.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ $.Values.validators.topologySpreadConstraints.whenUnsatisfiable }}

          labelSelector:
            matchLabels:
              app.kubernetes.io/component: validator
      {{- end }}

      containers:
        - name: besu

          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"

          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          securityContext:
            runAsUser: {{ $.Values.containerSecurityContext.runAsUser }}
            runAsGroup: {{ $.Values.containerSecurityContext.runAsGroup }}
            allowPrivilegeEscalation: {{ $.Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ $.Values.containerSecurityContext.readOnlyRootFilesystem }}

            capabilities:
              {{ toYaml $.Values.containerSecurityContext.capabilities | nindent 14 }}

          resources:
            requests:
              memory: "{{ $.Values.resources.validator.requests.memory }}"
              cpu: "{{ $.Values.resources.validator.requests.cpu }}"

            limits:
              memory: "{{ $.Values.resources.validator.limits.memory }}"
              cpu: "{{ $.Values.resources.validator.limits.cpu }}"

          args:
            - "--config-file=/etc/besu/config.toml"
            - "--genesis-file=/etc/genesis/genesis.json"
            - "--data-path=/data"

            - "--Xdns-enabled=true"
            - "--Xdns-update-enabled=true"

            - "--metrics-enabled={{ $.Values.validators.metrics.enabled }}"
            - "--metrics-host=0.0.0.0"
            - "--metrics-port={{ $.Values.validators.metrics.port }}"

            - "--host-allowlist=*"

            - "--version-compatibility-protection=false"

            {{- if and $.Values.validators.bootnode.enabled (eq .name $.Values.validators.bootnode.validator) }}
            - "--nat-method=NONE"
            {{- end }}

          ports:
            - containerPort: 30303
              name: discovery
              protocol: UDP

            - containerPort: 30303
              name: rlpx
              protocol: TCP

            {{- if $.Values.validators.metrics.enabled }}
            - containerPort: {{ $.Values.validators.metrics.port }}
              name: metrics
              protocol: TCP
            {{- end }}

          {{- if $.Values.validators.probes.startup.enabled }}
          startupProbe:
            tcpSocket:
              port: 30303

            failureThreshold: {{ $.Values.validators.probes.startup.failureThreshold }}
            periodSeconds: {{ $.Values.validators.probes.startup.periodSeconds }}
          {{- end }}

          {{- if $.Values.validators.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: 30303

            initialDelaySeconds: {{ $.Values.validators.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.validators.probes.readiness.periodSeconds }}
          {{- end }}

          {{- if $.Values.validators.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: 30303

            initialDelaySeconds: {{ $.Values.validators.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.validators.probes.liveness.periodSeconds }}
          {{- end }}

          volumeMounts:
            - mountPath: /secrets
              name: keys
              readOnly: true

            - mountPath: /etc/genesis
              name: genesis
              readOnly: true

            - mountPath: /etc/besu/static-nodes.json
              name: static-nodes
              subPath: static-nodes.json
              readOnly: true

            - mountPath: /etc/besu/config.toml
              name: validator-config
              subPath: config.toml
              readOnly: true

            - mountPath: /data
              name: besu-data

            {{- with $.Values.extraVolumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}

          env:
            {{- with $.Values.extraEnv }}
            {{ toYaml . | nindent 12 }}
            {{- end }}

      volumes:
        - name: genesis
          configMap:
            name: besu-genesis-configmap

        - name: static-nodes
          configMap:
            name: besu-static-nodes-json-configmap

        - name: validator-config
          configMap:
            name: besu-validators-config-toml-configmap

        - name: keys
          secret:
            secretName: besu-network-secret
            items:
              - key: {{ .key }}
                path: validator.key

        {{- with $.Values.extraVolumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: besu-data

      spec:
        accessModes:
          {{- toYaml $.Values.persistence.accessModes | nindent 10 }}

        storageClassName: {{ $.Values.storage.className }}

        resources:
          requests:
            storage: {{ $.Values.storage.size }}

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}

  labels:
    app: {{ .name }}
    app.kubernetes.io/name: besu
    app.kubernetes.io/component: validator

spec:

  {{- if $.Values.validators.service.headless }}
  clusterIP: None
  {{- end }}

  type: {{ $.Values.service.type }}

  selector:
    app: {{ .name }}

  ports:
    - name: discovery
      port: 30303
      protocol: UDP
      targetPort: 30303

    - name: rlpx
      port: 30303
      protocol: TCP
      targetPort: 30303

    {{- if $.Values.validators.metrics.enabled }}
    - name: metrics
      port: {{ $.Values.validators.metrics.port }}
      protocol: TCP
      targetPort: {{ $.Values.validators.metrics.port }}
    {{- end }}

{{- end }}