data-path="/data"

genesis-file="/etc/genesis/genesis.json"

node-private-key-file="/secrets/validator.key"

static-nodes-file="/etc/besu/static-nodes.json"

p2p-host="0.0.0.0"
p2p-port=30303

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

graphql-http-enabled=false

host-allowlist=["*"]

rpc-http-api=["ADMIN","ETH","NET","QBFT","WEB3","TXPOOL"]

sync-mode="FULL"

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

discovery-enabled=true

min-gas-price=0

logging="INFO"